language: go

go:
  - 1.7.4

before_install:
  - go get -t -v ./...
script:
  - go test -v -race -coverprofile=add_coverage.txt -covermode=count ./add/
  - go tool cover -func=add_coverage.txt
  - go test -v -race -coverprofile=div_coverage.txt -covermode=count ./div/
  - go tool cover -func=div_coverage.txt


after_success:
  - bash <(curl -s https://codecov.io/bash) -t c480f816-9c63-403f-9da5-316ba6b13a6b