language: go

go:
  - 1.7.4

before_install:
  - go get -t -v ./...
script:
  - go test -v -race -coverprofile cover.out add/
  - go tool cover -func=cover.out
  - go test -v -race -coverprofile cover.out div/
  - go tool cover -func=cover.out
  - go test -race -coverprofile=coverage.txt -covermode=count

after_success:
  - bash <(curl -s https://codecov.io/bash) -t c480f816-9c63-403f-9da5-316ba6b13a6b